// src/lib/components/gui/ProjectDetailModal.svelte
<script lang="ts">
	import type { Project } from '$lib/types';
	import { X, ExternalLink, Github, Check, Terminal, Image } from '@lucide/svelte';

	let { project, onClose } = $props<{
		project: Project;
		onClose: () => void;
	}>();

	let activeTab = $state<'overview' | 'screenshots'>('overview');

	function handleBackdropClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			onClose();
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			onClose();
		}
	}
</script>

<svelte:window onkeydown={handleKeydown} />

<div
	class="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4 animate-in fade-in duration-200"
	onclick={handleBackdropClick}
	onkeydown={(e) => e.key === 'Enter' && onClose()}
	role="dialog"
	aria-modal="true"
	tabindex="-1"
>
	<div
		class="bg-console border border-primary/30 rounded-lg max-w-5xl w-full max-h-[90vh] overflow-hidden shadow-[0_0_60px_rgba(0,255,156,0.2)] animate-in zoom-in-95 duration-200 flex flex-col"
	>
		<!-- Header -->
		<div class="bg-graphite border-b border-primary/20 p-6 flex items-start justify-between shrink-0">
			<div class="flex-1">
				<div class="flex items-center gap-3 mb-2">
					<h2 class="text-2xl font-bold text-primary">{project.name}</h2>
					<span
						class={`px-3 py-1 rounded text-xs font-mono uppercase font-bold ${
							project.status === 'ACTIVE'
								? 'bg-green-900/30 text-green-400 border border-green-500/30'
								: project.status === 'BETA'
									? 'bg-yellow-900/30 text-yellow-400 border border-yellow-500/30'
									: project.status === 'EXPERIMENTAL'
										? 'bg-blue-900/30 text-blue-400 border border-blue-500/30'
										: 'bg-graphite text-muted-foreground border border-border'
						}`}
					>
						{project.status}
					</span>
				</div>
				<p class="text-sm text-muted-foreground">{project.description}</p>
			</div>
			<button
				onclick={onClose}
				class="ml-4 p-2 hover:bg-primary/10 rounded transition-colors text-muted-foreground hover:text-primary shrink-0"
				aria-label="Close modal"
			>
				<X size={24} />
			</button>
		</div>

		<!-- Tabs -->
		<div class="border-b border-graphite/50 bg-dim/30 shrink-0">
			<div class="flex gap-1 px-6">
				<button
					onclick={() => (activeTab = 'overview')}
					class={`px-4 py-2.5 font-mono text-xs font-bold transition-all border-b-2 ${
						activeTab === 'overview'
							? 'border-primary text-primary'
							: 'border-transparent text-muted-foreground hover:text-foreground'
					}`}
				>
					<Terminal size={16} class="inline mr-2" />
					OVERVIEW
				</button>
				<button
					onclick={() => (activeTab = 'screenshots')}
					class={`px-4 py-2.5 font-mono text-xs font-bold transition-all border-b-2 ${
						activeTab === 'screenshots'
							? 'border-primary text-primary'
							: 'border-transparent text-muted-foreground hover:text-foreground'
					}`}
				>
					<Image size={16} class="inline mr-2" />
					SCREENSHOTS
				</button>
			</div>
		</div>

		<!-- Content -->
		<div class="p-6 space-y-6 overflow-y-auto custom-scrollbar flex-1">
			{#if activeTab === 'overview'}
				<!-- Long Description -->
				{#if project.longDescription}
				<div class="animate-in fade-in duration-300">
					<h3 class="text-lg font-bold text-foreground mb-3 flex items-center gap-2">
						<span class="w-1 h-5 bg-primary"></span>
						OVERVIEW
					</h3>
					<p class="text-muted-foreground leading-relaxed text-base">
							{project.longDescription}
						</p>
					</div>
				{/if}

				<!-- Features -->
				{#if project.features && project.features.length > 0}
				<div class="animate-in fade-in duration-300 delay-100">
					<h3 class="text-lg font-bold text-foreground mb-3 flex items-center gap-2">
						<span class="w-1 h-5 bg-primary"></span>
						KEY_FEATURES
					</h3>
						<ul class="grid grid-cols-1 md:grid-cols-2 gap-3">
						{#each project.features as feature}
							<li
								class="flex items-start gap-2.5 text-sm text-muted-foreground bg-dim/50 p-2.5 rounded border border-graphite/50 hover:border-primary/30 transition-colors"
							>
								<Check size={16} class="text-primary shrink-0 mt-0.5" />
								<span>{feature}</span>
								</li>
							{/each}
						</ul>
					</div>
				{/if}

				<!-- Tech Stack -->
				<div class="animate-in fade-in duration-300 delay-200">
					<h3 class="text-lg font-bold text-foreground mb-3 flex items-center gap-2">
						<span class="w-1 h-5 bg-primary"></span>
						TECH_STACK
					</h3>
					<div class="flex flex-wrap gap-2">
						{#each project.tech as tech}
							<span
								class="px-2.5 py-1.5 bg-dim border border-primary/20 rounded font-mono text-xs text-primary hover:bg-primary/10 hover:border-primary/40 transition-colors cursor-default"
							>
								{tech}
							</span>
						{/each}
					</div>
				</div>
			{:else if activeTab === 'screenshots'}
				<div class="animate-in fade-in duration-300">
					<h3 class="text-lg font-bold text-foreground mb-4 flex items-center gap-2">
						<span class="w-1 h-5 bg-primary"></span>
						PROJECT_GALLERY
					</h3>
					<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
						{#each [1, 2, 3, 4] as index}
							<div
								class="aspect-video bg-dim/50 border border-primary/20 rounded-lg overflow-hidden hover:border-primary/40 transition-all group relative"
							>
								<!-- Placeholder -->
								<div
									class="absolute inset-0 flex flex-col items-center justify-center text-muted-foreground/50"
								>
									<Image size={48} class="mb-3 text-primary/30" />
									<span class="font-mono text-xs">SCREENSHOT_{index}</span>
									<span class="font-mono text-[10px] mt-1 text-muted-foreground/30"
										>1920x1080</span
									>
								</div>
								<!-- Scanline effect -->
								<div
									class="absolute inset-0 bg-[linear-gradient(transparent_50%,rgba(0,255,156,0.02)_50%)] bg-size-[100%_4px] pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity"
								></div>
								<!-- Corner accents -->
								<div
									class="absolute top-2 left-2 w-4 h-4 border-t-2 border-l-2 border-primary/0 group-hover:border-primary/50 transition-colors"
								></div>
								<div
									class="absolute top-2 right-2 w-4 h-4 border-t-2 border-r-2 border-primary/0 group-hover:border-primary/50 transition-colors"
								></div>
								<div
									class="absolute bottom-2 left-2 w-4 h-4 border-b-2 border-l-2 border-primary/0 group-hover:border-primary/50 transition-colors"
								></div>
								<div
									class="absolute bottom-2 right-2 w-4 h-4 border-b-2 border-r-2 border-primary/0 group-hover:border-primary/50 transition-colors"
								></div>
							</div>
						{/each}
					</div>
					<p class="text-muted-foreground/60 text-sm mt-4 font-mono text-center">
						// Screenshot placeholders - Ready for integration
					</p>
				</div>
			{/if}
		</div>

		<!-- Footer with Links -->
		<div class="border-t border-graphite bg-dim/30 p-4 flex flex-wrap gap-3 shrink-0">
			{#if project.github}
				<a
					href={project.github}
					target="_blank"
					rel="noopener noreferrer"
					class="flex items-center gap-2 px-5 py-2.5 text-sm bg-primary text-console font-bold rounded hover:bg-primary/90 transition-all shadow-[0_0_20px_rgba(0,255,156,0.3)] hover:shadow-[0_0_30px_rgba(0,255,156,0.5)]"
				>
					<Github size={18} />
					VIEW SOURCE
				</a>
			{/if}
			{#if project.demo}
				<a
					href={project.demo}
					target="_blank"
					rel="noopener noreferrer"
					class="flex items-center gap-2 px-5 py-2.5 text-sm border border-graphite bg-dim text-foreground font-bold rounded hover:border-primary hover:text-primary hover:bg-primary/5 transition-all"
				>
					<ExternalLink size={18} />
					LIVE DEMO
				</a>
			{/if}
			<button
				onclick={onClose}
				class="flex items-center gap-2 px-5 py-2.5 text-sm ml-auto border border-graphite/50 bg-console text-muted-foreground font-bold rounded hover:border-muted-foreground hover:text-foreground transition-all"
			>
				<X size={18} />
				CLOSE
			</button>
		</div>
	</div>
</div>

// portfolio_old/components/ProjectDetailModal.tsx

import React, { useEffect } from 'react';
import { Project } from '../types';
import { X, Github, ExternalLink, Terminal, Cpu, Shield, Image as ImageIcon, AlertTriangle } from 'lucide-react';

interface ProjectDetailModalProps {
  project: Project;
  onClose: () => void;
}

export const ProjectDetailModal: React.FC<ProjectDetailModalProps> = ({ project, onClose }) => {
  // Prevent background scrolling when modal is open
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    
    window.addEventListener('keydown', handleKeyDown);
    document.body.style.overflow = 'hidden';
    
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = 'unset';
    };
  }, [onClose]);

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8">
      {/* Backdrop with CRT scanline effect */}
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-sm" 
        onClick={onClose}
      >
        <div className="absolute inset-0 bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] z-10 bg-[length:100%_2px,3px_100%] pointer-events-none opacity-20" />
      </div>

      {/* Modal Window */}
      <div className="relative w-full max-w-5xl bg-dim border border-graphite rounded-lg shadow-[0_0_50px_rgba(0,255,156,0.15)] flex flex-col max-h-[90vh] overflow-hidden animate-in fade-in zoom-in-95 duration-300 ring-1 ring-white/10">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-graphite bg-graphite/20 shrink-0">
            <div className="flex items-center gap-3">
                <Terminal className="text-matrix" size={20} />
                <div className="flex flex-col">
                    <h2 className="text-xl font-bold text-white tracking-wide uppercase leading-none">
                        {project.name}
                    </h2>
                    <span className="text-[10px] text-gray-500 font-mono mt-1 tracking-widest">PROJECT_DETAILS // ACCESS_GRANTED</span>
                </div>
            </div>
            <button 
                onClick={onClose}
                className="p-2 hover:bg-red-500/20 hover:text-red-400 rounded transition-colors text-gray-500 group"
            >
                <X size={24} className="group-hover:rotate-90 transition-transform duration-300" />
            </button>
        </div>

        {/* Content */}
        <div className="overflow-y-auto custom-scrollbar p-6 md:p-8">
            
            <div className="flex flex-col lg:flex-row gap-8">
                
                {/* Left Column: Info */}
                <div className="flex-1 space-y-8">
                    
                    {/* Status & Tags */}
                    <div className="flex flex-wrap items-center gap-3">
                        <span className={`px-3 py-1 rounded border text-xs font-bold uppercase tracking-wider ${
                            project.status === 'live' ? 'bg-green-900/30 text-green-400 border-green-800' : 
                            project.status === 'beta' ? 'bg-yellow-900/30 text-yellow-400 border-yellow-800' :
                            'bg-gray-800 text-gray-500 border-gray-700'
                        }`}>
                            STATUS: {project.status}
                        </span>
                        {project.tech.map(t => (
                            <span key={t} className="px-2 py-1 text-xs text-blue-300 bg-blue-900/10 border border-blue-900/30 rounded font-mono">
                                {t}
                            </span>
                        ))}
                    </div>

                    {/* Mission Briefing */}
                    <div className="bg-black/20 p-6 rounded border border-white/5 relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-1 h-full bg-matrix/50" />
                        <h3 className="text-matrix text-xs font-bold uppercase tracking-widest mb-3 flex items-center gap-2">
                            <Cpu size={14} /> Mission Briefing
                        </h3>
                        <p className="text-gray-300 leading-relaxed text-lg">
                            {project.longDescription || project.description}
                        </p>
                    </div>

                    {/* Features */}
                    {project.features && (
                        <div>
                            <h3 className="text-gray-500 text-xs font-bold uppercase tracking-widest mb-3 flex items-center gap-2">
                                <Shield size={14} /> Core Capabilities
                            </h3>
                            <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                {project.features.map((feature, idx) => (
                                    <li key={idx} className="flex items-start gap-3 text-gray-400 text-sm bg-graphite/20 p-3 rounded hover:bg-graphite/40 transition-colors border border-transparent hover:border-graphite/50">
                                        <span className="text-matrix mt-0.5">▹</span>
                                        <span className="leading-relaxed">{feature}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {/* Actions */}
                    <div className="flex flex-wrap gap-4 pt-6 border-t border-graphite/50">
                        {project.demoLink && (
                            <a 
                                href={project.demoLink} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex-1 min-w-[160px] flex items-center justify-center gap-2 px-6 py-4 bg-matrix text-console font-bold rounded hover:bg-white hover:scale-[1.02] transition-all shadow-[0_0_20px_rgba(0,255,156,0.2)] group"
                            >
                                <ExternalLink size={18} className="group-hover:rotate-45 transition-transform" />
                                INITIATE DEMO
                            </a>
                        )}
                        {project.repoLink && (
                            <a 
                                href={project.repoLink}
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex-1 min-w-[160px] flex items-center justify-center gap-2 px-6 py-4 bg-transparent border border-graphite text-white font-bold rounded hover:border-white hover:bg-white/5 hover:scale-[1.02] transition-all"
                            >
                                <Github size={18} />
                                SOURCE CODE
                            </a>
                        )}
                    </div>

                </div>

                {/* Right Column: Visuals */}
                <div className="lg:w-[340px] xl:w-[400px] space-y-6 shrink-0">
                    <div>
                        <h3 className="text-xs text-gray-500 font-bold uppercase tracking-widest mb-3 flex items-center gap-2">
                             <ImageIcon size={14} /> Visual Feeds
                        </h3>
                        
                        <div className="space-y-4">
                            {/* Placeholder Image 1 */}
                            <div className="aspect-video bg-black/60 border border-graphite rounded flex flex-col items-center justify-center relative overflow-hidden group cursor-not-allowed">
                                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/diagmonds-light.png')] opacity-5"></div>
                                <div className="absolute inset-0 bg-gradient-to-t from-black/90 to-transparent"></div>
                                
                                {/* Animated scanline */}
                                <div className="absolute top-0 left-0 w-full h-1 bg-matrix/30 shadow-[0_0_10px_rgba(0,255,156,0.5)] animate-scanline opacity-50"></div>
                                
                                <div className="text-center z-10 opacity-60 group-hover:opacity-100 transition-opacity">
                                    <AlertTriangle className="w-10 h-10 text-yellow-500 mx-auto mb-2" />
                                    <span className="text-xs font-mono text-yellow-500 tracking-wider block">FEED ENCRYPTED</span>
                                    <span className="text-[10px] text-gray-600 font-mono">AUTH_REQUIRED</span>
                                </div>
                            </div>

                            {/* Placeholder Image 2 */}
                             <div className="aspect-video bg-black/60 border border-graphite rounded flex flex-col items-center justify-center relative overflow-hidden group cursor-not-allowed">
                                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-5"></div>
                                
                                <div className="text-center z-10 opacity-40 group-hover:opacity-80 transition-opacity">
                                    <ImageIcon className="w-8 h-8 text-gray-600 mx-auto mb-2" />
                                    <span className="text-xs font-mono text-gray-500 tracking-wider block">SIGNAL LOST</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Metadata Panel */}
                    <div className="bg-dim border border-graphite/50 p-4 rounded text-xs font-mono space-y-3 text-gray-500">
                         <div className="flex justify-between border-b border-graphite/30 pb-2">
                             <span>DEPLOY_REGION</span>
                             <span className="text-matrix">US-EAST-1</span>
                         </div>
                         <div className="flex justify-between border-b border-graphite/30 pb-2">
                             <span>SECURITY_LEVEL</span>
                             <span className="text-yellow-500">HIGH</span>
                         </div>
                         <div className="flex justify-between">
                             <span>UPTIME</span>
                             <span className="text-white">99.99%</span>
                         </div>
                    </div>
                </div>

            </div>
        </div>
      </div>
    </div>
  );
};
