// src/lib/components/terminal/PromptLine.svelte
<script lang="ts">
	import { ChevronRight } from '@lucide/svelte';
	import { onMount, tick } from 'svelte';
	
	let {
		onSubmit,
		cwd = '~',
		disabled = false
	} = $props<{
		onSubmit: (command: string) => void;
		cwd?: string;
		disabled?: boolean;
	}>();
	
	let input = $state('');
	let inputRef: HTMLInputElement;
	
	let historyIndex = $state(-1);
	let commandHistory = $state<string[]>([]);
	
	async function handleSubmit(e: Event) {
		e.preventDefault();
		if (!input.trim() || disabled) return;
		
		onSubmit(input.trim());
		commandHistory = [...commandHistory, input.trim()];
		historyIndex = -1;
		input = '';
		
		// Refocus input after submission and DOM update
		await tick();
		setTimeout(() => inputRef?.focus(), 50);
	}
	
	function handleKeyDown(e: KeyboardEvent) {
		if (e.key === 'ArrowUp') {
			e.preventDefault();
			if (commandHistory.length === 0) return;
			
			if (historyIndex === -1) {
				historyIndex = commandHistory.length - 1;
			} else if (historyIndex > 0) {
				historyIndex--;
			}
			input = commandHistory[historyIndex] || '';
		} else if (e.key === 'ArrowDown') {
			e.preventDefault();
			if (historyIndex === -1) return;
			
			if (historyIndex < commandHistory.length - 1) {
				historyIndex++;
				input = commandHistory[historyIndex] || '';
			} else {
				historyIndex = -1;
				input = '';
			}
		}
	}
	
	function handleContainerClick() {
		inputRef?.focus();
	}
	
	function handleContainerKeyPress(e: KeyboardEvent) {
		if (e.key === 'Enter' || e.key === ' ') {
			inputRef?.focus();
		}
	}
	
	onMount(() => {
		inputRef?.focus();
	});
</script>

<form onsubmit={handleSubmit}>
	<div
		class="flex items-center gap-2 py-2"
		onclick={handleContainerClick}
		onkeypress={handleContainerKeyPress}
		role="button"
		tabindex="-1"
	>
		<!-- Prompt prefix -->
		<span class="text-warning text-sm hidden md:inline">guest@portfolio</span>
		<span class="text-muted-foreground hidden md:inline">:</span>
		<span class="text-blue-400 text-sm">{cwd}</span>
		<ChevronRight class="w-3 h-3 text-matrix" />
		
		<!-- Input with custom cursor -->
		<div class="flex-1 relative">
			<input
				bind:this={inputRef}
				bind:value={input}
				onkeydown={handleKeyDown}
				disabled={disabled}
				type="text"
				class="w-full bg-transparent border-none outline-none text-foreground caret-matrix font-mono text-sm md:text-base"
				autocomplete="off"
				spellcheck="false"
			/>
		</div>
	</div>
</form>

// portfolio_old/components/PromptLine.tsx
import React, { useState, forwardRef, KeyboardEvent } from 'react';
import { ChevronRight } from 'lucide-react';

interface PromptLineProps {
  cwd: string;
  onCommand: (cmd: string) => void;
  isProcessing: boolean;
}

export const PromptLine = forwardRef<HTMLInputElement, PromptLineProps>(({ cwd, onCommand, isProcessing }, ref) => {
  const [inputValue, setInputValue] = useState('');
  const [commandHistoryIndex, setCommandHistoryIndex] = useState(-1);

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && !isProcessing) {
      onCommand(inputValue);
      setInputValue('');
      setCommandHistoryIndex(-1);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  if (isProcessing) {
    return null; // Hide prompt while processing
  }

  return (
    <div className="flex items-center w-full mt-2 group text-lg md:text-base">
        <span className="text-warning mr-2 font-bold hidden md:inline">guest@portfolio</span>
        <span className="text-gray-500 mr-2 hidden md:inline">:</span>
        <span className="text-blue-400 mr-2 font-bold shrink-0">{cwd}</span>
        <ChevronRight className="w-4 h-4 text-matrix mr-1 shrink-0 animate-pulse" />
        
        <div className="relative flex-1">
            {/* Visible Fake Input */}
            <div className="absolute inset-0 pointer-events-none flex items-center text-matrix whitespace-pre text-shadow-glow">
                {inputValue}
                <span className="w-2.5 h-5 bg-matrix ml-[1px] animate-blink inline-block align-middle shadow-[0_0_8px_rgba(0,255,156,0.8)]"></span>
            </div>

            {/* Hidden Real Input for Accessibility & Mobile */}
            <input
                ref={ref}
                type="text"
                value={inputValue}
                onChange={handleChange}
                onKeyDown={handleKeyDown}
                className="w-full opacity-0 bg-transparent border-none outline-none text-transparent caret-transparent h-6 cursor-text"
                autoComplete="off"
                autoFocus
                spellCheck={false}
            />
        </div>
    </div>
  );
});

PromptLine.displayName = 'PromptLine';
